version: '{branch}-ci-{build}'

os: Visual Studio 2015

clone_depth: 1


init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - set PATH=%PATH%;C:\cygwin\bin;


install:
  - git submodule update --init --recursive
  - nuget install Allegro -Version 5.1.13.1 -ExcludeVersion
  - nuget install AllegroDeps -Version 1.4.0 -ExcludeVersion
  - set A5_INC_DIR=%APPVEYOR_BUILD_FOLDER%\Allegro\build\native\include
  - set A5_LIB_DIR=%APPVEYOR_BUILD_FOLDER%\Allegro\build\native\v140\x64\lib
  - set A5DEPS_LIB_DIR=%APPVEYOR_BUILD_FOLDER%\AllegroDeps\build\native\v140\x64\deps\lib


build_script:
  - set MRUBY_CONFIG=minigame_build_config.rb
  - ruby mruby\minirake -f mruby\Rakefile


test_script:
  - cd mruby
  - set MRUBY_CONFIG=..\minigame_build_config.rb
  - ruby .\minirake test


artifacts:
  - path: mruby\bin
