version: '{branch}-ci-{build}'

os: Visual Studio 2015

shallow_clone: true

clone_depth: 1

#install:

before_build:
  - git submodule update --init --recursive

build_script:
  - cd mruby
  - set MRUBY_CONFIG=..\minigame_build_config.rb
  - ruby .\minirake

test_script:
  - ruby .\minirake test
